
name: 'activity_schema_demo'
version: '1.0.0'
config-version: 2


profile: 'activity_schema_demo'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"



models:
  activity_schema_demo:
    staging:
      +materialized: view
    customers:
      activities:
        +materialized: activity
      aggregations:
        +materialized: aggregatin
      datasets:
        +materialized: table

vars:
  dbt_activity_schema:
    customer_activity_stream:
      entity_id: customer_id